win support
versatica/mediasoup-demo pull request #56
Opened 2019-08-29 07:35 UTC by haiyangwu

using the win style socket path

2019-08-29 09:41 UTC, ibc commented
Amazing. Let's go first for the PR in mediasoup and come back to this one later.

2019-08-29 09:43 UTC, ibc commented
This is absolutely amazing, thanks!

However we have zero experience in Windows so we'll make lot of questions and may request some changes. Let's go step by step.

2019-08-29 13:11 UTC, ibc requested changes

2019-08-29 13:11 UTC, ibc commented on server/lib/interactiveServer.js
> +const path = require('path');
Let's move system modules to the top of the file.

2019-08-29 13:11 UTC, ibc commented on server/lib/interactiveServer.js
> +const SOCKET_PATH = os.platform() === 'win32'? SOCKET_PATH_WIN : SOCKET_PATH_UIX
Let's move these constants after `require()` lines above.

2019-09-22 22:51 UTC, TemaSM approved these changes
LGTM ✔️

2019-10-20 20:35 UTC, ibc requested changes

2019-10-20 20:35 UTC, ibc commented on .gitignore
> +/.vscode/
Add line jump at the end of the file.

2019-10-20 20:35 UTC, ibc commented on server/lib/interactiveClient.js
> +const SOCKET_PATH_UIX = '/tmp/mediasoup-demo.sock';
Please rename (fix it) to `SOCKET_PATH_UNIX`.

2019-10-20 20:35 UTC, ibc commented on server/lib/interactiveServer.js
> +const SOCKET_PATH_UIX = '/tmp/mediasoup-demo.sock';
Please rename (fix it) to SOCKET_PATH_UNIX.

2019-10-21 12:03 UTC, ibc approved these changes

2019-10-21 12:03 UTC, merged

2019-10-21 12:04 UTC, ibc commented
Thanks a lot, merged.